import type {DeepSpaceSignal} from "@/src/types/deepSpaceNetwork";

export const DEEP_SPACE_SIGNALS: DeepSpaceSignal[] = [
    {
        id: "voyager1",
        image: "https://images-assets.nasa.gov/image/PIA17046/PIA17046~orig.jpg",
        href: "/missions/voyager1",
        x: "33%",
        y: "12%",
        align: "right",
    },
    {
        id: "jamesWebb",
        image: "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001982/GSFC_20171208_Archive_e001982~orig.jpg",
        href: "/missions/james-webb",
        x: "65%",
        y: "20%",
        align: "right",
    },
    {
        id: "newHorizons",
        image: "https://images-assets.nasa.gov/image/PIA09234/PIA09234~orig.jpg",
        href: "/missions/new-horizons",
        x: "23%",
        y: "36%",
        align: "left",
    },
    {
        id: "iss",
        image: "https://images-assets.nasa.gov/image/iss056e201248/iss056e201248~orig.jpg",
        href: "/live/iss",
        x: "76%",
        y: "39%",
        align: "right",
    },
    {
        id: "hubble",
        image: "https://images-assets.nasa.gov/image/0201238/0201238~orig.jpg",
        href: "/missions/hubble",
        x: "77%",
        y: "62%",
        align: "right",
    },
    {
        id: "mro",
        image: "https://images-assets.nasa.gov/image/PIA04916/PIA04916~orig.jpg",
        href: "/missions/mars-reconnaissance-orbiter",
        x: "25%",
        y: "67%",
        align: "left",
    },
    {
        id: "perseverance",
        image: "https://images-assets.nasa.gov/image/PIA23764/PIA23764~orig.jpg",
        href: "/missions/perseverance",
        x: "43%",
        y: "80%",
        align: "right",
    },
    {
        id: "artemis",
        image: "https://images-assets.nasa.gov/image/artemis-i-launch/artemis-i-launch~orig.jpg",
        href: "/missions/artemis",
        x: "66%",
        y: "78%",
        align: "right",
    },
];