export type EarthTab = "overview" | "events" | "epic" | "layers";

export type EarthLocale = {
    badge: string;
    title: string;
    subtitle: string;
    overview: string;
    events: string;
    epic: string;
    layers: string;
    activeEvents: string;
    closedEvents: string;
    epicImages: string;
    satelliteLayers: string;
    latestEvents: string;
    latestEarthImages: string;
    gibsLayers: string;
    source: string;
    status: string;
    category: string;
    coordinates: string;
    date: string;
    noData: string;
    details: {
        back: string;
        nasaEvent: string;
        loading: string;
        notFound: string;
        descriptionFallback: string;
        id: string;
        status: string;
        latestDate: string;
        coordinates: string;
        geometryPoints: string;
        sources: string;
        geometryTrack: string;
        rawPayload: string;
        point: string;
        type: string;
        date: string;
        source: string;
        category: string;
        open: string;
        closed: string;
        viewDetails: string;
        viewImage: string;
        openSource: string;
    };
};